/**
 * 読み上げ (TTS) の発音辞書 — 型と組み込み初期辞書（純データ・副作用なし）。
 *
 * 日本語音声エンジンは英字略語/英単語を誤読する（例: "AI" → 「あい」）。
 * 読み上げ直前に本文をこの辞書でカタカナ読みへ置換して補正する（tts-normalize.ts）。
 * ここはデータ層なので置換ロジックや localStorage には触れない。
 */

export interface DictEntry {
  /** 元表記。例: "AI" / "Google"。 */
  match: string;
  /** カタカナ読み。例: "エーアイ" / "グーグル"。 */
  reading: string;
  /**
   * 綴りの大小を区別するか。
   * true  = 略語向け（大文字綴りだけを拾い、"aid"/"Air" 等の小文字英単語を誤爆させない）。
   * false = 一般英単語向け（"google"/"Google" どちらも拾う）。
   */
  caseSensitive: boolean;
}

const abbr = (match: string, reading: string): DictEntry => ({
  match,
  reading,
  caseSensitive: true,
});
const word = (match: string, reading: string): DictEntry => ({
  match,
  reading,
  caseSensitive: false,
});

/**
 * 組み込み初期辞書。ユーザー辞書（tts-dict-store）とマージして使う（ユーザー優先）。
 * v1 は誤読が目立つ IT 略語＋主要固有名詞に絞る。過不足はユーザーが Settings で補える。
 */
export const BUILTIN_DICT: DictEntry[] = [
  // --- 英字略語（大小区別あり） ---
  abbr("AI", "エーアイ"),
  abbr("UI", "ユーアイ"),
  abbr("UX", "ユーエックス"),
  abbr("API", "エーピーアイ"),
  abbr("URL", "ユーアールエル"),
  abbr("LLM", "エルエルエム"),
  abbr("RSS", "アールエスエス"),
  abbr("HTTP", "エイチティーティーピー"),
  abbr("HTTPS", "エイチティーティーピーエス"),
  abbr("CPU", "シーピーユー"),
  abbr("GPU", "ジーピーユー"),
  abbr("NPU", "エヌピーユー"),
  abbr("OS", "オーエス"),
  abbr("SDK", "エスディーケー"),
  abbr("CLI", "シーエルアイ"),
  abbr("IDE", "アイディーイー"),
  abbr("JSON", "ジェイソン"),
  abbr("HTML", "エイチティーエムエル"),
  abbr("CSS", "シーエスエス"),
  abbr("SQL", "エスキューエル"),
  abbr("DB", "ディービー"),
  abbr("IoT", "アイオーティー"),
  abbr("SNS", "エスエヌエス"),
  abbr("PDF", "ピーディーエフ"),
  abbr("USB", "ユーエスビー"),
  abbr("PC", "ピーシー"),
  abbr("ID", "アイディー"),
  abbr("GPT", "ジーピーティー"),
  abbr("ML", "エムエル"),
  abbr("VR", "ブイアール"),
  abbr("AR", "エーアール"),
  abbr("OSS", "オーエスエス"),
  abbr("CI", "シーアイ"),
  // --- 英字略語 追加分（Web/インフラ/AI・大小区別あり） ---
  abbr("JWT", "ジェイダブリューティー"),
  abbr("OAuth", "オーオース"),
  abbr("SSO", "エスエスオー"),
  abbr("DNS", "ディーエヌエス"),
  abbr("CDN", "シーディーエヌ"),
  abbr("TCP", "ティーシーピー"),
  abbr("UDP", "ユーディーピー"),
  abbr("IP", "アイピー"),
  abbr("SSH", "エスエスエイチ"),
  abbr("TLS", "ティーエルエス"),
  abbr("SSL", "エスエスエル"),
  abbr("VPN", "ブイピーエヌ"),
  abbr("REST", "レスト"),
  abbr("gRPC", "ジーアールピーシー"),
  abbr("GraphQL", "グラフキューエル"),
  abbr("SPA", "エスピーエー"),
  abbr("PWA", "ピーダブリューエー"),
  abbr("SSR", "エスエスアール"),
  abbr("SSG", "エスエスジー"),
  abbr("DOM", "ドム"),
  abbr("npm", "エヌピーエム"),
  abbr("CSV", "シーエスブイ"),
  abbr("XML", "エックスエムエル"),
  abbr("YAML", "ヤムル"),
  abbr("SVG", "エスブイジー"),
  abbr("JPEG", "ジェイペグ"),
  abbr("GIF", "ギフ"),
  abbr("WebP", "ウェブピー"),
  abbr("K8s", "ケーエイツ"),
  abbr("VM", "ブイエム"),
  abbr("RAM", "ラム"),
  abbr("ROM", "ロム"),
  abbr("SSD", "エスエスディー"),
  abbr("HDD", "エイチディーディー"),
  abbr("LAN", "ラン"),
  abbr("WAN", "ワン"),
  abbr("RAG", "ラグ"),
  abbr("NLP", "エヌエルピー"),
  abbr("OCR", "オーシーアール"),
  abbr("TTS", "ティーティーエス"),
  abbr("ASR", "エーエスアール"),
  abbr("SaaS", "サース"),
  abbr("PaaS", "パース"),
  abbr("IaaS", "イアース"),
  abbr("AWS", "エーダブリューエス"),
  abbr("GCP", "ジーシーピー"),
  abbr("CRUD", "クラッド"),
  abbr("UUID", "ユーユーアイディー"),
  abbr("ORM", "オーアールエム"),
  abbr("JVM", "ジェイブイエム"),
  abbr("XSS", "エックスエスエス"),
  abbr("2FA", "ツーエフエー"),
  abbr("MFA", "エムエフエー"),
  // --- 一般英単語・固有名詞（大小区別なし） ---
  word("OpenAI", "オープンエーアイ"),
  word("ChatGPT", "チャットジーピーティー"),
  word("Anthropic", "アンソロピック"),
  word("Claude", "クロード"),
  word("Google", "グーグル"),
  word("GitHub", "ギットハブ"),
  word("Amazon", "アマゾン"),
  word("Microsoft", "マイクロソフト"),
  word("Apple", "アップル"),
  word("YouTube", "ユーチューブ"),
  word("iPhone", "アイフォン"),
  word("iPad", "アイパッド"),
  word("Android", "アンドロイド"),
  word("Windows", "ウィンドウズ"),
  word("Linux", "リナックス"),
  word("Chrome", "クローム"),
  // --- 固有名詞 追加分（クラウド/ツール/企業・大小区別なし） ---
  word("Azure", "アジュール"),
  word("Meta", "メタ"),
  word("Netflix", "ネットフリックス"),
  word("Slack", "スラック"),
  word("Notion", "ノーション"),
  word("Figma", "フィグマ"),
  word("Docker", "ドッカー"),
  word("Kubernetes", "クバネティス"),
  word("Node.js", "ノードジェイエス"),
  word("Deno", "ディーノ"),
  word("Python", "パイソン"),
  word("Java", "ジャバ"),
  word("JavaScript", "ジャバスクリプト"),
  word("TypeScript", "タイプスクリプト"),
  word("Rust", "ラスト"),
  word("Golang", "ゴーラン"),
  word("Kotlin", "コトリン"),
  word("Swift", "スイフト"),
  word("React", "リアクト"),
  word("Vue", "ビュー"),
  word("Svelte", "スベルト"),
  word("Angular", "アンギュラー"),
  word("Next.js", "ネクストジェイエス"),
  word("Vite", "ヴィート"),
  word("Nginx", "エンジンエックス"),
  word("PostgreSQL", "ポストグレスキューエル"),
  word("Redis", "レディス"),
  word("MySQL", "マイエスキューエル"),
  word("SQLite", "エスキューライト"),
  word("MongoDB", "モンゴディービー"),
  word("Ubuntu", "ウブントゥ"),
  word("Nvidia", "エヌビディア"),
  word("Intel", "インテル"),
  word("Qualcomm", "クアルコム"),
  word("Samsung", "サムスン"),
  word("Adobe", "アドビ"),
  word("Oracle", "オラクル"),
  word("Salesforce", "セールスフォース"),
  word("Discord", "ディスコード"),
  word("Reddit", "レディット"),
  word("Spotify", "スポティファイ"),
  word("Tesla", "テスラ"),
  word("Gemini", "ジェミニ"),
  word("Copilot", "コパイロット"),
  word("Cursor", "カーソル"),
  word("Vercel", "ヴァーセル"),
  word("Netlify", "ネットリファイ"),
  word("Cloudflare", "クラウドフレア"),
];
